// Code generated by SQLBoiler 4.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	OAuths           string
	QueueItems       string
	Refs             string
	Repositories     string
	Runs             string
	Sessions         string
	Submissions      string
	Subscriptions    string
	Tasks            string
	UserCapabilities string
	UserErrors       string
	Users            string
}{
	OAuths:           "o_auths",
	QueueItems:       "queue_items",
	Refs:             "refs",
	Repositories:     "repositories",
	Runs:             "runs",
	Sessions:         "sessions",
	Submissions:      "submissions",
	Subscriptions:    "subscriptions",
	Tasks:            "tasks",
	UserCapabilities: "user_capabilities",
	UserErrors:       "user_errors",
	Users:            "users",
}
