// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/tinyci/ci-agents/ci-gen/grpc/types/submission.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Submission struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	HeadRef              *Ref                 `protobuf:"bytes,2,opt,name=headRef,proto3" json:"headRef,omitempty"`
	BaseRef              *Ref                 `protobuf:"bytes,3,opt,name=baseRef,proto3" json:"baseRef,omitempty"`
	User                 *User                `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Submission) Reset()         { *m = Submission{} }
func (m *Submission) String() string { return proto.CompactTextString(m) }
func (*Submission) ProtoMessage()    {}
func (*Submission) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f00c03eb97056e8, []int{0}
}

func (m *Submission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Submission.Unmarshal(m, b)
}
func (m *Submission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Submission.Marshal(b, m, deterministic)
}
func (m *Submission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Submission.Merge(m, src)
}
func (m *Submission) XXX_Size() int {
	return xxx_messageInfo_Submission.Size(m)
}
func (m *Submission) XXX_DiscardUnknown() {
	xxx_messageInfo_Submission.DiscardUnknown(m)
}

var xxx_messageInfo_Submission proto.InternalMessageInfo

func (m *Submission) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Submission) GetHeadRef() *Ref {
	if m != nil {
		return m.HeadRef
	}
	return nil
}

func (m *Submission) GetBaseRef() *Ref {
	if m != nil {
		return m.BaseRef
	}
	return nil
}

func (m *Submission) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Submission) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type SubmissionList struct {
	Submissions          []*Submission `protobuf:"bytes,1,rep,name=submissions,proto3" json:"submissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SubmissionList) Reset()         { *m = SubmissionList{} }
func (m *SubmissionList) String() string { return proto.CompactTextString(m) }
func (*SubmissionList) ProtoMessage()    {}
func (*SubmissionList) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f00c03eb97056e8, []int{1}
}

func (m *SubmissionList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmissionList.Unmarshal(m, b)
}
func (m *SubmissionList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmissionList.Marshal(b, m, deterministic)
}
func (m *SubmissionList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmissionList.Merge(m, src)
}
func (m *SubmissionList) XXX_Size() int {
	return xxx_messageInfo_SubmissionList.Size(m)
}
func (m *SubmissionList) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmissionList.DiscardUnknown(m)
}

var xxx_messageInfo_SubmissionList proto.InternalMessageInfo

func (m *SubmissionList) GetSubmissions() []*Submission {
	if m != nil {
		return m.Submissions
	}
	return nil
}

func init() {
	proto.RegisterType((*Submission)(nil), "types.Submission")
	proto.RegisterType((*SubmissionList)(nil), "types.SubmissionList")
}

func init() {
	proto.RegisterFile("github.com/tinyci/ci-agents/ci-gen/grpc/types/submission.proto", fileDescriptor_9f00c03eb97056e8)
}

var fileDescriptor_9f00c03eb97056e8 = []byte{
	// 294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0x3d, 0x6b, 0xf3, 0x30,
	0x14, 0x85, 0x71, 0x3e, 0xde, 0x97, 0xca, 0x10, 0xa8, 0x26, 0xe3, 0xa5, 0x26, 0x74, 0xf0, 0x12,
	0x09, 0x92, 0xa1, 0x81, 0x42, 0xa1, 0x85, 0x6e, 0x9d, 0xd4, 0x76, 0xe9, 0x26, 0xdb, 0xd7, 0x8a,
	0x20, 0xb6, 0x8c, 0xae, 0x3c, 0xe4, 0xf7, 0xf5, 0x8f, 0x15, 0xcb, 0x76, 0x1d, 0xe8, 0xe4, 0xed,
	0xa2, 0xf3, 0x9c, 0xfb, 0x71, 0x44, 0x9e, 0x94, 0x76, 0xa7, 0x36, 0x63, 0xb9, 0xa9, 0xb8, 0xd3,
	0xf5, 0x25, 0xd7, 0x3c, 0xd7, 0x3b, 0xa9, 0xa0, 0x76, 0xd8, 0x55, 0x0a, 0x6a, 0xae, 0x6c, 0x93,
	0x73, 0x77, 0x69, 0x00, 0x39, 0xb6, 0x59, 0xa5, 0x11, 0xb5, 0xa9, 0x59, 0x63, 0x8d, 0x33, 0x74,
	0xed, 0xdf, 0xe3, 0xc7, 0xab, 0x36, 0xca, 0x9c, 0x65, 0xad, 0xb8, 0xd7, 0xb3, 0xb6, 0xe4, 0x4d,
	0x6f, 0x75, 0xba, 0x02, 0x74, 0xb2, 0x6a, 0xa6, 0xaa, 0xef, 0x11, 0x3f, 0xcc, 0xdb, 0xc1, 0x42,
	0x39, 0x18, 0x8f, 0xf3, 0x8c, 0x2d, 0x82, 0xed, 0x9d, 0xdb, 0xef, 0x80, 0x90, 0xf7, 0xdf, 0x5b,
	0xe8, 0x86, 0x2c, 0x74, 0x11, 0x05, 0x49, 0x90, 0x2e, 0xc5, 0x42, 0x17, 0xf4, 0x9e, 0xfc, 0x3f,
	0x81, 0x2c, 0x04, 0x94, 0xd1, 0x22, 0x09, 0xd2, 0x70, 0x4f, 0x98, 0x6f, 0xc1, 0x04, 0x94, 0x62,
	0x94, 0x3a, 0x2a, 0x93, 0x08, 0x1d, 0xb5, 0xfc, 0x4b, 0x0d, 0x12, 0xbd, 0x23, 0xab, 0x6e, 0x70,
	0xb4, 0xf2, 0x48, 0x38, 0x20, 0x9f, 0x08, 0x56, 0x78, 0x81, 0x1e, 0xc9, 0x4d, 0x6e, 0x41, 0x3a,
	0x28, 0x9e, 0x5d, 0xb4, 0xf6, 0x54, 0xcc, 0x94, 0x31, 0xea, 0x0c, 0x6c, 0x0c, 0x91, 0x7d, 0x8c,
	0x99, 0x89, 0x09, 0xde, 0xbe, 0x92, 0xcd, 0x74, 0xc4, 0x9b, 0x46, 0x47, 0x0f, 0x24, 0x9c, 0xbe,
	0x08, 0xa3, 0x20, 0x59, 0xa6, 0xe1, 0xfe, 0x76, 0x98, 0x39, 0xb1, 0xe2, 0x9a, 0x7a, 0xe1, 0x5f,
	0xbb, 0x59, 0x41, 0x66, 0xff, 0xfc, 0x5a, 0x87, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc0, 0xef,
	0x45, 0xf4, 0x3d, 0x02, 0x00, 0x00,
}
