// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/tinyci/ci-agents/ci-gen/grpc/types/user.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// User is ... a user record
type User struct {
	Id               int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username         string               `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	LastScannedRepos *timestamp.Timestamp `protobuf:"bytes,3,opt,name=lastScannedRepos,proto3" json:"lastScannedRepos,omitempty"`
	Errors           []*UserError         `protobuf:"bytes,4,rep,name=errors,proto3" json:"errors,omitempty"`
	// JSON corresponding to the oauth2 response from github when first signing
	// up; this contains an access and refresh token. Encrypted with the token
	// key.
	TokenJSON            []byte   `protobuf:"bytes,5,opt,name=tokenJSON,proto3" json:"tokenJSON,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_eaa9e911a83fd97b, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetLastScannedRepos() *timestamp.Timestamp {
	if m != nil {
		return m.LastScannedRepos
	}
	return nil
}

func (m *User) GetErrors() []*UserError {
	if m != nil {
		return m.Errors
	}
	return nil
}

func (m *User) GetTokenJSON() []byte {
	if m != nil {
		return m.TokenJSON
	}
	return nil
}

// UserError is the pre-converted UserError record. It is later converted to a types.Error.
type UserError struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserID               int64    `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserError) Reset()         { *m = UserError{} }
func (m *UserError) String() string { return proto.CompactTextString(m) }
func (*UserError) ProtoMessage()    {}
func (*UserError) Descriptor() ([]byte, []int) {
	return fileDescriptor_eaa9e911a83fd97b, []int{1}
}

func (m *UserError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserError.Unmarshal(m, b)
}
func (m *UserError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserError.Marshal(b, m, deterministic)
}
func (m *UserError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserError.Merge(m, src)
}
func (m *UserError) XXX_Size() int {
	return xxx_messageInfo_UserError.Size(m)
}
func (m *UserError) XXX_DiscardUnknown() {
	xxx_messageInfo_UserError.DiscardUnknown(m)
}

var xxx_messageInfo_UserError proto.InternalMessageInfo

func (m *UserError) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserError) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *UserError) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

// List of UserError
type UserErrors struct {
	Errors               []*UserError `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UserErrors) Reset()         { *m = UserErrors{} }
func (m *UserErrors) String() string { return proto.CompactTextString(m) }
func (*UserErrors) ProtoMessage()    {}
func (*UserErrors) Descriptor() ([]byte, []int) {
	return fileDescriptor_eaa9e911a83fd97b, []int{2}
}

func (m *UserErrors) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserErrors.Unmarshal(m, b)
}
func (m *UserErrors) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserErrors.Marshal(b, m, deterministic)
}
func (m *UserErrors) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserErrors.Merge(m, src)
}
func (m *UserErrors) XXX_Size() int {
	return xxx_messageInfo_UserErrors.Size(m)
}
func (m *UserErrors) XXX_DiscardUnknown() {
	xxx_messageInfo_UserErrors.DiscardUnknown(m)
}

var xxx_messageInfo_UserErrors proto.InternalMessageInfo

func (m *UserErrors) GetErrors() []*UserError {
	if m != nil {
		return m.Errors
	}
	return nil
}

// List of Users
type UserList struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserList) Reset()         { *m = UserList{} }
func (m *UserList) String() string { return proto.CompactTextString(m) }
func (*UserList) ProtoMessage()    {}
func (*UserList) Descriptor() ([]byte, []int) {
	return fileDescriptor_eaa9e911a83fd97b, []int{3}
}

func (m *UserList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserList.Unmarshal(m, b)
}
func (m *UserList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserList.Marshal(b, m, deterministic)
}
func (m *UserList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserList.Merge(m, src)
}
func (m *UserList) XXX_Size() int {
	return xxx_messageInfo_UserList.Size(m)
}
func (m *UserList) XXX_DiscardUnknown() {
	xxx_messageInfo_UserList.DiscardUnknown(m)
}

var xxx_messageInfo_UserList proto.InternalMessageInfo

func (m *UserList) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "types.User")
	proto.RegisterType((*UserError)(nil), "types.UserError")
	proto.RegisterType((*UserErrors)(nil), "types.UserErrors")
	proto.RegisterType((*UserList)(nil), "types.UserList")
}

func init() {
	proto.RegisterFile("github.com/tinyci/ci-agents/ci-gen/grpc/types/user.proto", fileDescriptor_eaa9e911a83fd97b)
}

var fileDescriptor_eaa9e911a83fd97b = []byte{
	// 322 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0x4f, 0x4b, 0x03, 0x31,
	0x10, 0xc5, 0x49, 0xb7, 0x5b, 0xba, 0x53, 0x91, 0x12, 0x44, 0x96, 0xe2, 0x61, 0xdd, 0xd3, 0x5e,
	0x9a, 0x40, 0x05, 0x11, 0xbc, 0x89, 0x0a, 0x15, 0x51, 0x48, 0xf5, 0xe2, 0x6d, 0xbb, 0x8d, 0x31,
	0xd8, 0x4d, 0x96, 0x24, 0x3d, 0xf4, 0xeb, 0xf9, 0xc9, 0x24, 0xd9, 0xfe, 0x83, 0x82, 0xe0, 0x6d,
	0x66, 0x1e, 0xef, 0xcd, 0x6f, 0x12, 0xb8, 0x11, 0xd2, 0x7d, 0xad, 0xe6, 0xa4, 0xd2, 0x35, 0x75,
	0x52, 0xad, 0x2b, 0x49, 0x2b, 0x39, 0x2e, 0x05, 0x57, 0xce, 0xfa, 0x4a, 0x70, 0x45, 0x85, 0x69,
	0x2a, 0xea, 0xd6, 0x0d, 0xb7, 0x74, 0x65, 0xb9, 0x21, 0x8d, 0xd1, 0x4e, 0xe3, 0x38, 0x4c, 0x46,
	0xb7, 0x07, 0x01, 0x42, 0x2f, 0x4b, 0x25, 0x68, 0xd0, 0xe7, 0xab, 0x4f, 0xda, 0xb4, 0x26, 0x27,
	0x6b, 0x6e, 0x5d, 0x59, 0x37, 0xfb, 0xaa, 0xcd, 0xc8, 0x7f, 0x10, 0x74, 0xdf, 0x2d, 0x37, 0xf8,
	0x14, 0x3a, 0x72, 0x91, 0xa2, 0x0c, 0x15, 0x11, 0xeb, 0xc8, 0x05, 0x1e, 0x41, 0xdf, 0xaf, 0x52,
	0x65, 0xcd, 0xd3, 0x4e, 0x86, 0x8a, 0x84, 0xed, 0x7a, 0xfc, 0x08, 0xc3, 0x65, 0x69, 0xdd, 0xac,
	0x2a, 0x95, 0xe2, 0x0b, 0xc6, 0x1b, 0x6d, 0xd3, 0x28, 0x43, 0xc5, 0x60, 0x32, 0x22, 0x42, 0x6b,
	0xb1, 0xe4, 0x64, 0x4b, 0x40, 0xde, 0xb6, 0x0b, 0xd9, 0x91, 0x07, 0x17, 0xd0, 0xe3, 0xc6, 0x68,
	0x63, 0xd3, 0x6e, 0x16, 0x15, 0x83, 0xc9, 0x90, 0x04, 0x5c, 0xe2, 0x81, 0x1e, 0xbc, 0xc0, 0x36,
	0x3a, 0xbe, 0x80, 0xc4, 0xe9, 0x6f, 0xae, 0x9e, 0x66, 0xaf, 0x2f, 0x69, 0x9c, 0xa1, 0xe2, 0x84,
	0xed, 0x07, 0xf9, 0x14, 0x92, 0x9d, 0xe5, 0xe8, 0x90, 0x73, 0xe8, 0x79, 0xf0, 0xe9, 0x7d, 0x38,
	0x23, 0x62, 0x9b, 0x0e, 0x9f, 0x41, 0x1c, 0xc2, 0x03, 0x79, 0xc2, 0xda, 0x26, 0xbf, 0x06, 0xd8,
	0x45, 0x1d, 0x02, 0xa2, 0xbf, 0x01, 0xf3, 0x31, 0xf4, 0xfd, 0xf0, 0x59, 0x5a, 0x87, 0x2f, 0x21,
	0xf6, 0x3b, 0xb6, 0xa6, 0xc1, 0x81, 0x89, 0xb5, 0xca, 0x1d, 0xfd, 0x18, 0xff, 0xeb, 0xdb, 0xe7,
	0xbd, 0xf0, 0xa0, 0x57, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x1f, 0x18, 0x4f, 0x86, 0x2e, 0x02,
	0x00, 0x00,
}
