// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/services/queue/server.proto

package queue

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	types "github.com/tinyci/ci-agents/ci-gen/grpc/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Submission controls the submission of branches and pull requests. Some
// (noted) properties are not externally modifiable, so they will result in a
// noop if set.
type Submission struct {
	Parent               string   `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Fork                 string   `protobuf:"bytes,2,opt,name=fork,proto3" json:"fork,omitempty"`
	Headsha              string   `protobuf:"bytes,3,opt,name=headsha,proto3" json:"headsha,omitempty"`
	Basesha              string   `protobuf:"bytes,4,opt,name=basesha,proto3" json:"basesha,omitempty"`
	SubmittedBy          string   `protobuf:"bytes,5,opt,name=submitted_by,json=submittedBy,proto3" json:"submitted_by,omitempty"`
	PullRequest          int64    `protobuf:"varint,6,opt,name=pull_request,json=pullRequest,proto3" json:"pull_request,omitempty"`
	All                  bool     `protobuf:"varint,7,opt,name=all,proto3" json:"all,omitempty"`
	Manual               bool     `protobuf:"varint,8,opt,name=manual,proto3" json:"manual,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Submission) Reset()         { *m = Submission{} }
func (m *Submission) String() string { return proto.CompactTextString(m) }
func (*Submission) ProtoMessage()    {}
func (*Submission) Descriptor() ([]byte, []int) {
	return fileDescriptor_18dba3f4b885f33f, []int{0}
}

func (m *Submission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Submission.Unmarshal(m, b)
}
func (m *Submission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Submission.Marshal(b, m, deterministic)
}
func (m *Submission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Submission.Merge(m, src)
}
func (m *Submission) XXX_Size() int {
	return xxx_messageInfo_Submission.Size(m)
}
func (m *Submission) XXX_DiscardUnknown() {
	xxx_messageInfo_Submission.DiscardUnknown(m)
}

var xxx_messageInfo_Submission proto.InternalMessageInfo

func (m *Submission) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *Submission) GetFork() string {
	if m != nil {
		return m.Fork
	}
	return ""
}

func (m *Submission) GetHeadsha() string {
	if m != nil {
		return m.Headsha
	}
	return ""
}

func (m *Submission) GetBasesha() string {
	if m != nil {
		return m.Basesha
	}
	return ""
}

func (m *Submission) GetSubmittedBy() string {
	if m != nil {
		return m.SubmittedBy
	}
	return ""
}

func (m *Submission) GetPullRequest() int64 {
	if m != nil {
		return m.PullRequest
	}
	return 0
}

func (m *Submission) GetAll() bool {
	if m != nil {
		return m.All
	}
	return false
}

func (m *Submission) GetManual() bool {
	if m != nil {
		return m.Manual
	}
	return false
}

func init() {
	proto.RegisterType((*Submission)(nil), "queue.Submission")
}

func init() { proto.RegisterFile("grpc/services/queue/server.proto", fileDescriptor_18dba3f4b885f33f) }

var fileDescriptor_18dba3f4b885f33f = []byte{
	// 414 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xc1, 0x6e, 0x13, 0x31,
	0x10, 0xcd, 0x36, 0x4d, 0xda, 0xb8, 0xad, 0x54, 0x8c, 0x54, 0xad, 0x72, 0x0a, 0x39, 0x45, 0x48,
	0xd8, 0x12, 0x01, 0xd4, 0x13, 0x87, 0x02, 0x42, 0xb9, 0x20, 0x48, 0x6e, 0x5c, 0x22, 0xef, 0x66,
	0xea, 0x58, 0x78, 0xed, 0xed, 0x7a, 0x8c, 0xd8, 0xaf, 0xe0, 0x07, 0xf9, 0x18, 0xe4, 0xd9, 0x2d,
	0xb4, 0x07, 0x2a, 0x7a, 0x59, 0xcd, 0x7b, 0xcf, 0x6f, 0x66, 0x76, 0x66, 0xd8, 0x4c, 0x37, 0x75,
	0x29, 0x03, 0x34, 0xdf, 0x4d, 0x09, 0x41, 0xde, 0x44, 0x88, 0x40, 0x10, 0x1a, 0x51, 0x37, 0x1e,
	0x3d, 0x1f, 0x11, 0x37, 0x5d, 0x6a, 0x83, 0xfb, 0x58, 0x88, 0xd2, 0x57, 0x52, 0x7b, 0xab, 0x9c,
	0x96, 0xa4, 0x17, 0xf1, 0x5a, 0xd6, 0xd8, 0xd6, 0x10, 0x24, 0x54, 0x35, 0xb6, 0xdd, 0xb7, 0xf3,
	0x4e, 0xdf, 0xde, 0x31, 0xa1, 0x71, 0x6d, 0x69, 0x64, 0x69, 0x5e, 0x28, 0x0d, 0x0e, 0x43, 0x8a,
	0x34, 0x38, 0x49, 0x0d, 0x74, 0x09, 0xa8, 0xd2, 0xd6, 0x20, 0x54, 0xbd, 0xff, 0xcd, 0xe3, 0xfc,
	0x66, 0xd7, 0xf9, 0xe6, 0xbf, 0x32, 0xc6, 0x36, 0xb1, 0xa8, 0x4c, 0x08, 0xc6, 0x3b, 0x7e, 0xc1,
	0xc6, 0xb5, 0x6a, 0xc0, 0x61, 0x9e, 0xcd, 0xb2, 0xc5, 0x64, 0xdd, 0x23, 0xce, 0xd9, 0xe1, 0xb5,
	0x6f, 0xbe, 0xe5, 0x07, 0xc4, 0x52, 0xcc, 0x73, 0x76, 0xb4, 0x07, 0xb5, 0x0b, 0x7b, 0x95, 0x0f,
	0x89, 0xbe, 0x85, 0x49, 0x29, 0x54, 0x80, 0xa4, 0x1c, 0x76, 0x4a, 0x0f, 0xf9, 0x33, 0x76, 0x1a,
	0x52, 0x35, 0x44, 0xd8, 0x6d, 0x8b, 0x36, 0x1f, 0x91, 0x7c, 0xf2, 0x87, 0xbb, 0x6a, 0xd3, 0x93,
	0x3a, 0x5a, 0xbb, 0x6d, 0xe0, 0x26, 0x42, 0xc0, 0x7c, 0x3c, 0xcb, 0x16, 0xc3, 0xf5, 0x49, 0xe2,
	0xd6, 0x1d, 0xc5, 0xcf, 0xd9, 0x50, 0x59, 0x9b, 0x1f, 0xcd, 0xb2, 0xc5, 0xf1, 0x3a, 0x85, 0xa9,
	0xef, 0x4a, 0xb9, 0xa8, 0x6c, 0x7e, 0x4c, 0x64, 0x8f, 0x5e, 0xfe, 0x3c, 0x60, 0xa3, 0x2f, 0x69,
	0x56, 0xfc, 0x15, 0x9b, 0x7c, 0x8e, 0xb8, 0x41, 0x85, 0x31, 0xf0, 0x33, 0x41, 0x63, 0x10, 0x1d,
	0x9c, 0x5e, 0x08, 0xed, 0xbd, 0xb6, 0x20, 0x6e, 0xf7, 0x24, 0x3e, 0xa4, 0xd5, 0xcc, 0x07, 0xfc,
	0x92, 0x9d, 0x7d, 0x82, 0x1f, 0x48, 0x29, 0x56, 0x08, 0x15, 0x7f, 0xda, 0x3b, 0x89, 0xe9, 0xfb,
	0x99, 0x9e, 0xdf, 0x25, 0xd3, 0xb3, 0xf9, 0x80, 0xbf, 0x66, 0x63, 0x9a, 0x2b, 0xf2, 0x27, 0x82,
	0xb6, 0x25, 0xfe, 0x8e, 0xf9, 0x81, 0x82, 0x4b, 0x36, 0xd9, 0x00, 0xbe, 0x53, 0xae, 0x04, 0xcb,
	0x4f, 0xfb, 0xbc, 0x2b, 0x87, 0xab, 0xf7, 0x0f, 0x98, 0x9e, 0xb3, 0xc9, 0xc7, 0x7f, 0x98, 0xee,
	0xff, 0xe9, 0x7c, 0x70, 0x75, 0xf9, 0xf5, 0xbf, 0x4f, 0xe5, 0xfe, 0xad, 0x17, 0x63, 0xaa, 0xbb,
	0xfc, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xfd, 0xa9, 0x4e, 0xdc, 0x09, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueueClient is the client API for Queue service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueueClient interface {
	PutStatus(ctx context.Context, in *types.Status, opts ...grpc.CallOption) (*empty.Empty, error)
	NextQueueItem(ctx context.Context, in *types.QueueRequest, opts ...grpc.CallOption) (*types.QueueItem, error)
	Submit(ctx context.Context, in *Submission, opts ...grpc.CallOption) (*empty.Empty, error)
	SetCancel(ctx context.Context, in *types.IntID, opts ...grpc.CallOption) (*empty.Empty, error)
	GetCancel(ctx context.Context, in *types.IntID, opts ...grpc.CallOption) (*types.Status, error)
}

type queueClient struct {
	cc *grpc.ClientConn
}

func NewQueueClient(cc *grpc.ClientConn) QueueClient {
	return &queueClient{cc}
}

func (c *queueClient) PutStatus(ctx context.Context, in *types.Status, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/queue.Queue/PutStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueClient) NextQueueItem(ctx context.Context, in *types.QueueRequest, opts ...grpc.CallOption) (*types.QueueItem, error) {
	out := new(types.QueueItem)
	err := c.cc.Invoke(ctx, "/queue.Queue/NextQueueItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueClient) Submit(ctx context.Context, in *Submission, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/queue.Queue/Submit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueClient) SetCancel(ctx context.Context, in *types.IntID, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/queue.Queue/SetCancel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueClient) GetCancel(ctx context.Context, in *types.IntID, opts ...grpc.CallOption) (*types.Status, error) {
	out := new(types.Status)
	err := c.cc.Invoke(ctx, "/queue.Queue/GetCancel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueueServer is the server API for Queue service.
type QueueServer interface {
	PutStatus(context.Context, *types.Status) (*empty.Empty, error)
	NextQueueItem(context.Context, *types.QueueRequest) (*types.QueueItem, error)
	Submit(context.Context, *Submission) (*empty.Empty, error)
	SetCancel(context.Context, *types.IntID) (*empty.Empty, error)
	GetCancel(context.Context, *types.IntID) (*types.Status, error)
}

// UnimplementedQueueServer can be embedded to have forward compatible implementations.
type UnimplementedQueueServer struct {
}

func (*UnimplementedQueueServer) PutStatus(ctx context.Context, req *types.Status) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutStatus not implemented")
}
func (*UnimplementedQueueServer) NextQueueItem(ctx context.Context, req *types.QueueRequest) (*types.QueueItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NextQueueItem not implemented")
}
func (*UnimplementedQueueServer) Submit(ctx context.Context, req *Submission) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Submit not implemented")
}
func (*UnimplementedQueueServer) SetCancel(ctx context.Context, req *types.IntID) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetCancel not implemented")
}
func (*UnimplementedQueueServer) GetCancel(ctx context.Context, req *types.IntID) (*types.Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCancel not implemented")
}

func RegisterQueueServer(s *grpc.Server, srv QueueServer) {
	s.RegisterService(&_Queue_serviceDesc, srv)
}

func _Queue_PutStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.Status)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServer).PutStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/queue.Queue/PutStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServer).PutStatus(ctx, req.(*types.Status))
	}
	return interceptor(ctx, in, info, handler)
}

func _Queue_NextQueueItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.QueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServer).NextQueueItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/queue.Queue/NextQueueItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServer).NextQueueItem(ctx, req.(*types.QueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Queue_Submit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Submission)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServer).Submit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/queue.Queue/Submit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServer).Submit(ctx, req.(*Submission))
	}
	return interceptor(ctx, in, info, handler)
}

func _Queue_SetCancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.IntID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServer).SetCancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/queue.Queue/SetCancel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServer).SetCancel(ctx, req.(*types.IntID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Queue_GetCancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.IntID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServer).GetCancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/queue.Queue/GetCancel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServer).GetCancel(ctx, req.(*types.IntID))
	}
	return interceptor(ctx, in, info, handler)
}

var _Queue_serviceDesc = grpc.ServiceDesc{
	ServiceName: "queue.Queue",
	HandlerType: (*QueueServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutStatus",
			Handler:    _Queue_PutStatus_Handler,
		},
		{
			MethodName: "NextQueueItem",
			Handler:    _Queue_NextQueueItem_Handler,
		},
		{
			MethodName: "Submit",
			Handler:    _Queue_Submit_Handler,
		},
		{
			MethodName: "SetCancel",
			Handler:    _Queue_SetCancel_Handler,
		},
		{
			MethodName: "GetCancel",
			Handler:    _Queue_GetCancel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/services/queue/server.proto",
}
