/**
 * uisvc
 * API for the user interface service; the service that is directly responsible for presenting data to users. This service typically runs at the border, and leverages session cookies or authentication tokens that we generate for users. It also is responsible for handling the act of oauth and user creation through its login hooks. uisvc typically talks to the datasvc and other services to accomplish its goal, it does not save anything locally or carry state. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Run from './Run';

/**
 * The QueueItem model module.
 * @module model/QueueItem
 * @version 1.0.0
 */
class QueueItem {
    /**
     * Constructs a new <code>QueueItem</code>.
     * @alias module:model/QueueItem
     */
    constructor() { 
        
        QueueItem.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>QueueItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/QueueItem} obj Optional instance to populate.
     * @return {module:model/QueueItem} The populated <code>QueueItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new QueueItem();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('run')) {
                obj['run'] = Run.constructFromObject(data['run']);
            }
            if (data.hasOwnProperty('running')) {
                obj['running'] = ApiClient.convertToType(data['running'], 'Boolean');
            }
            if (data.hasOwnProperty('running_on')) {
                obj['running_on'] = ApiClient.convertToType(data['running_on'], 'String');
            }
            if (data.hasOwnProperty('started_at')) {
                obj['started_at'] = ApiClient.convertToType(data['started_at'], 'Date');
            }
            if (data.hasOwnProperty('queue_name')) {
                obj['queue_name'] = ApiClient.convertToType(data['queue_name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
QueueItem.prototype['id'] = undefined;

/**
 * @member {module:model/Run} run
 */
QueueItem.prototype['run'] = undefined;

/**
 * @member {Boolean} running
 */
QueueItem.prototype['running'] = undefined;

/**
 * @member {String} running_on
 */
QueueItem.prototype['running_on'] = undefined;

/**
 * @member {Date} started_at
 */
QueueItem.prototype['started_at'] = undefined;

/**
 * @member {String} queue_name
 */
QueueItem.prototype['queue_name'] = undefined;






export default QueueItem;

