// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/tinyci/ci-agents/grpc/types/repository.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/struct"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Repository is the model for a github repository.
type Repository struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Private              bool     `protobuf:"varint,3,opt,name=private,proto3" json:"private,omitempty"`
	Disabled             bool     `protobuf:"varint,4,opt,name=disabled,proto3" json:"disabled,omitempty"`
	Owner                *User    `protobuf:"bytes,5,opt,name=owner,proto3" json:"owner,omitempty"`
	AutoCreated          bool     `protobuf:"varint,6,opt,name=autoCreated,proto3" json:"autoCreated,omitempty"`
	HookSecret           string   `protobuf:"bytes,7,opt,name=hookSecret,proto3" json:"hookSecret,omitempty"`
	Github               []byte   `protobuf:"bytes,8,opt,name=github,proto3" json:"github,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Repository) Reset()         { *m = Repository{} }
func (m *Repository) String() string { return proto.CompactTextString(m) }
func (*Repository) ProtoMessage()    {}
func (*Repository) Descriptor() ([]byte, []int) {
	return fileDescriptor_45934fea59af315f, []int{0}
}

func (m *Repository) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Repository.Unmarshal(m, b)
}
func (m *Repository) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Repository.Marshal(b, m, deterministic)
}
func (m *Repository) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Repository.Merge(m, src)
}
func (m *Repository) XXX_Size() int {
	return xxx_messageInfo_Repository.Size(m)
}
func (m *Repository) XXX_DiscardUnknown() {
	xxx_messageInfo_Repository.DiscardUnknown(m)
}

var xxx_messageInfo_Repository proto.InternalMessageInfo

func (m *Repository) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Repository) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Repository) GetPrivate() bool {
	if m != nil {
		return m.Private
	}
	return false
}

func (m *Repository) GetDisabled() bool {
	if m != nil {
		return m.Disabled
	}
	return false
}

func (m *Repository) GetOwner() *User {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *Repository) GetAutoCreated() bool {
	if m != nil {
		return m.AutoCreated
	}
	return false
}

func (m *Repository) GetHookSecret() string {
	if m != nil {
		return m.HookSecret
	}
	return ""
}

func (m *Repository) GetGithub() []byte {
	if m != nil {
		return m.Github
	}
	return nil
}

type RepositoryList struct {
	List                 []*Repository `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RepositoryList) Reset()         { *m = RepositoryList{} }
func (m *RepositoryList) String() string { return proto.CompactTextString(m) }
func (*RepositoryList) ProtoMessage()    {}
func (*RepositoryList) Descriptor() ([]byte, []int) {
	return fileDescriptor_45934fea59af315f, []int{1}
}

func (m *RepositoryList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepositoryList.Unmarshal(m, b)
}
func (m *RepositoryList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepositoryList.Marshal(b, m, deterministic)
}
func (m *RepositoryList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepositoryList.Merge(m, src)
}
func (m *RepositoryList) XXX_Size() int {
	return xxx_messageInfo_RepositoryList.Size(m)
}
func (m *RepositoryList) XXX_DiscardUnknown() {
	xxx_messageInfo_RepositoryList.DiscardUnknown(m)
}

var xxx_messageInfo_RepositoryList proto.InternalMessageInfo

func (m *RepositoryList) GetList() []*Repository {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*Repository)(nil), "types.Repository")
	proto.RegisterType((*RepositoryList)(nil), "types.RepositoryList")
}

func init() {
	proto.RegisterFile("github.com/tinyci/ci-agents/grpc/types/repository.proto", fileDescriptor_45934fea59af315f)
}

var fileDescriptor_45934fea59af315f = []byte{
	// 307 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x50, 0x3d, 0x4f, 0x23, 0x31,
	0x14, 0x94, 0xf3, 0x7d, 0x6f, 0x4f, 0x91, 0xce, 0xc5, 0xc9, 0x4a, 0x71, 0xf2, 0x45, 0x02, 0xb9,
	0x61, 0x2d, 0x82, 0x50, 0x7a, 0x68, 0xa9, 0x8c, 0x68, 0xe8, 0xbc, 0xbb, 0x8f, 0x8d, 0x45, 0xb2,
	0x5e, 0xd9, 0x6f, 0x41, 0xf9, 0xbd, 0xfc, 0x11, 0x24, 0x6f, 0x48, 0x52, 0xa6, 0xb2, 0x67, 0xc6,
	0xe3, 0x37, 0x6f, 0x60, 0x5d, 0x3b, 0xda, 0x74, 0x45, 0x5e, 0xfa, 0x9d, 0x26, 0xd7, 0xec, 0x4b,
	0xa7, 0x4b, 0x77, 0x63, 0x6b, 0x6c, 0x28, 0xea, 0x3a, 0xb4, 0xa5, 0xa6, 0x7d, 0x8b, 0x51, 0x07,
	0x6c, 0x7d, 0x74, 0xe4, 0xc3, 0x3e, 0x6f, 0x83, 0x27, 0xcf, 0xc7, 0x89, 0x5f, 0xdc, 0x9f, 0xf9,
	0x6b, 0xbf, 0xb5, 0x4d, 0xad, 0x93, 0x5e, 0x74, 0x6f, 0xba, 0xed, 0xad, 0x91, 0x42, 0x57, 0xd2,
	0xe1, 0xe8, 0xdd, 0x8b, 0xdb, 0x0b, 0xc7, 0x76, 0x11, 0x43, 0x6f, 0x59, 0x7e, 0x31, 0x00, 0x73,
	0x4c, 0xc1, 0xe7, 0x30, 0x70, 0x95, 0x60, 0x92, 0xa9, 0xa1, 0x19, 0xb8, 0x8a, 0x73, 0x18, 0x35,
	0x76, 0x87, 0x62, 0x20, 0x99, 0xfa, 0x65, 0xd2, 0x9d, 0x0b, 0x98, 0xb6, 0xc1, 0x7d, 0x58, 0x42,
	0x31, 0x94, 0x4c, 0xcd, 0xcc, 0x0f, 0xe4, 0x0b, 0x98, 0x55, 0x2e, 0xda, 0x62, 0x8b, 0x95, 0x18,
	0x25, 0xe9, 0x88, 0xf9, 0x7f, 0x18, 0xfb, 0xcf, 0x06, 0x83, 0x18, 0x4b, 0xa6, 0xb2, 0x55, 0x96,
	0xa7, 0x28, 0xf9, 0x4b, 0xc4, 0x60, 0x7a, 0x85, 0x4b, 0xc8, 0x6c, 0x47, 0xfe, 0x31, 0xa0, 0x25,
	0xac, 0xc4, 0x24, 0xfd, 0x70, 0x4e, 0xf1, 0x7f, 0x00, 0x1b, 0xef, 0xdf, 0x9f, 0xb1, 0x0c, 0x48,
	0x62, 0x9a, 0x42, 0x9d, 0x31, 0xfc, 0x2f, 0x4c, 0xfa, 0x0a, 0xc4, 0x4c, 0x32, 0xf5, 0xdb, 0x1c,
	0xd0, 0x72, 0x0d, 0xf3, 0xd3, 0x92, 0x4f, 0x2e, 0x12, 0xbf, 0x82, 0xd1, 0xd6, 0x45, 0x12, 0x4c,
	0x0e, 0x55, 0xb6, 0xfa, 0x73, 0x48, 0x73, 0x7a, 0x64, 0x92, 0xfc, 0xa0, 0x5e, 0xaf, 0x2f, 0xeb,
	0xb4, 0x98, 0xa4, 0x3e, 0xef, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff, 0xb5, 0xc0, 0xf7, 0x68, 0xfb,
	0x01, 0x00, 0x00,
}
